# Generated by Django 6.0.7 on 2026-08-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='reason',
            field=models.CharField(choices=[('no_show', 'No show'), ('incomplete', 'Incomplete session'), ('quality', 'Service quality'), ('hours', 'Hours disagreement'), ('behavior', 'Inappropriate behavior'), ('other', 'Other')], max_length=30, verbose_name='سبب النزاع'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('under_review', 'Under review'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='open', max_length=30, verbose_name='حالة النزاع'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('exchange_request', 'Exchange request'), ('exchange_accepted', 'Exchange accepted'), ('exchange_rejected', 'Exchange rejected'), ('session_reminder', 'Session reminder'), ('session_completed', 'Session completed'), ('wallet', 'Wallet'), ('message', 'New message'), ('review', 'Review'), ('dispute', 'Dispute'), ('system', 'System')], default='system', max_length=30, verbose_name='نوع الإشعار'),
        ),
    ]
