# Generated by Django 6.0.7 on 2026-08-26 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_dispute_reason_alter_dispute_status_and_more'),
        ('exchanges', '0003_alter_provideravailability_day_of_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('offer', 'Offer'), ('answer', 'Answer'), ('candidate', 'ICE candidate'), ('hangup', 'Hang up')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_signals', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_signals', to='exchanges.session', verbose_name='Session')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
