# Generated by Django 6.0.7 on 2026-08-27 23:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_callsignal'),
        ('exchanges', '0005_finalize_legacy_transferred_exchanges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='callsignal',
            index=models.Index(fields=['session', 'created_at'], name='call_signal_session_time_idx'),
        ),
    ]
