# Generated by Django 6.0.7 on 2026-08-27 23:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_callsignal_call_signal_session_time_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='client_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='Client message ID'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_id__isnull', False)), fields=('conversation', 'sender', 'client_id'), name='unique_sender_client_message'),
        ),
    ]
