# Generated by Django 6.0.7 on 2026-08-28 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_message_client_id_and_more'),
        ('exchanges', '0005_finalize_legacy_transferred_exchanges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField(editable=False, unique=True)),
                ('call_type', models.CharField(choices=[('audio', 'Audio call'), ('video', 'Video call')], max_length=10)),
                ('status', models.CharField(choices=[('ringing', 'Calling'), ('answered', 'Answered'), ('ended', 'Call ended'), ('missed', 'Missed call'), ('declined', 'Call declined'), ('cancelled', 'Call cancelled')], default='ringing', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_call_events', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_events', to='communications.conversation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_events', to='exchanges.session')),
            ],
            options={
                'ordering': ['started_at', 'id'],
                'indexes': [models.Index(fields=['conversation', 'started_at'], name='call_event_conv_time_idx'), models.Index(fields=['status', 'ended_at'], name='call_event_status_end_idx')],
            },
        ),
    ]
