# Generated by Django 6.0.7 on 2026-08-28 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_callevent'),
        ('exchanges', '0005_finalize_legacy_transferred_exchanges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='exchanges.session', verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='reason',
            field=models.CharField(choices=[('no_teaching', 'The other participant did not teach the agreed content'), ('no_show', 'The other participant did not attend the session'), ('ended_early', 'The session ended before the agreed time'), ('poor_teaching_style', 'The teaching style was not suitable'), ('inappropriate_behavior', 'There was inappropriate behavior'), ('different_content', 'The content differed from the offer description'), ('technical_issue', 'Technical issue'), ('other', 'Other'), ('incomplete', 'Incomplete session'), ('quality', 'Service quality'), ('hours', 'Hours disagreement'), ('behavior', 'Inappropriate behavior')], max_length=30, verbose_name='سبب النزاع'),
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.UniqueConstraint(condition=models.Q(('session__isnull', False)), fields=('session',), name='unique_dispute_per_session'),
        ),
    ]
