# Generated by Django 6.0.7 on 2026-08-28 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_dispute_session_alter_dispute_reason_and_more'),
        ('exchanges', '0006_session_reward_processed_session_rewarded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSystemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('reward', 'Session reward'), ('dispute', 'Session issue')], max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_system_events', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_events', to='communications.conversation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_events', to='exchanges.session')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('session', 'event_type'), name='unique_session_system_event_type')],
            },
        ),
    ]
