# Generated by Django 6.1 on 2026-08-23 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_hours', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='عدد الساعات')),
                ('message', models.TextField(blank=True, verbose_name='رسالة الطلب')),
                ('requested_date', models.DateField(blank=True, null=True, verbose_name='التاريخ المقترح')),
                ('requested_time', models.TimeField(blank=True, null=True, verbose_name='الوقت المقترح')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الموافقة'), ('accepted', 'تمت الموافقة'), ('rejected', 'مرفوض'), ('scheduled', 'تم تحديد الموعد'), ('in_progress', 'الجلسة جارية'), ('completed', 'مكتمل'), ('cancelled', 'ملغي'), ('disputed', 'يوجد نزاع')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_requests', to='skills.skilloffer', verbose_name='عرض المهارة')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_exchange_requests', to=settings.AUTH_USER_MODEL, verbose_name='مقدم المهارة')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_exchange_requests', to=settings.AUTH_USER_MODEL, verbose_name='طالب المهارة')),
            ],
            options={
                'verbose_name': 'طلب تبادل',
                'verbose_name_plural': 'طلبات التبادل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=30, verbose_name='الحالة السابقة')),
                ('new_status', models.CharField(max_length=30, verbose_name='الحالة الجديدة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التغيير')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_changes', to=settings.AUTH_USER_MODEL, verbose_name='تم التعديل بواسطة')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='exchanges.exchangerequest', verbose_name='طلب التبادل')),
            ],
            options={
                'verbose_name': 'سجل تبادل',
                'verbose_name_plural': 'سجل التبادلات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')], verbose_name='اليوم')),
                ('start_time', models.TimeField(verbose_name='وقت البداية')),
                ('end_time', models.TimeField(verbose_name='وقت النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاح')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'وقت توفر',
                'verbose_name_plural': 'أوقات التوفر',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_start', models.DateTimeField(verbose_name='بداية الجلسة')),
                ('scheduled_end', models.DateTimeField(verbose_name='نهاية الجلسة')),
                ('delivery_method', models.CharField(choices=[('online', 'عن بعد'), ('in_person', 'حضوري')], default='online', max_length=20, verbose_name='طريقة الجلسة')),
                ('meeting_link', models.URLField(blank=True, verbose_name='رابط الجلسة')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='مكان الجلسة')),
                ('status', models.CharField(choices=[('scheduled', 'مجدولة'), ('in_progress', 'جارية'), ('waiting_confirmation', 'بانتظار التأكيد'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة'), ('disputed', 'متنازع عليها')], default='scheduled', max_length=30, verbose_name='حالة الجلسة')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت البدء الفعلي')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإكمال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('exchange', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='exchanges.exchangerequest', verbose_name='طلب التبادل')),
            ],
            options={
                'verbose_name': 'جلسة',
                'verbose_name_plural': 'الجلسات',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='SessionConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False, verbose_name='تم تأكيد الجلسة')),
                ('issue_reported', models.BooleanField(default=False, verbose_name='تم الإبلاغ عن مشكلة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('confirmed_at', models.DateTimeField(auto_now=True, verbose_name='وقت التأكيد')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='exchanges.session', verbose_name='الجلسة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_confirmations', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تأكيد جلسة',
                'verbose_name_plural': 'تأكيدات الجلسات',
                'constraints': [models.UniqueConstraint(fields=('session', 'user'), name='unique_session_confirmation')],
            },
        ),
    ]
