# Generated by Django 6.0.7 on 2026-08-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0002_alter_exchangerequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provideravailability',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='اليوم'),
        ),
    ]
