# Generated by Django 6.0.7 on 2026-08-26 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_session_directions(apps, schema_editor):
    Session = apps.get_model('exchanges', 'Session')
    ExchangeRequest = apps.get_model('exchanges', 'ExchangeRequest')
    for session in Session.objects.select_related('exchange').iterator():
        exchange = session.exchange
        session.learner_id = exchange.requester_id
        session.provider_id = exchange.provider_id
        session.offer_id = exchange.offer_id
        if session.status == 'waiting_confirmation':
            session.status = 'awaiting_confirmation'
        session.save(update_fields=['learner', 'provider', 'offer', 'status'])
    ExchangeRequest.objects.filter(status='scheduled').update(status='accepted')


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0003_alter_provideravailability_day_of_week'),
        ('skills', '0003_alter_skilloffer_delivery_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='reverse_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reverse_exchange_requests', to='skills.skilloffer', verbose_name='Skill exchange offer'),
        ),
        migrations.AddField(
            model_name='session',
            name='learner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Learner'),
        ),
        migrations.AddField(
            model_name='session',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='skills.skilloffer', verbose_name='Skill offer'),
        ),
        migrations.AddField(
            model_name='session',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teaching_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_progress', 'In progress'), ('awaiting_confirmation', 'Awaiting confirmation'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=30, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='session',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exchanges.exchangerequest', verbose_name='طلب التبادل'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In progress'), ('awaiting_confirmation', 'Awaiting confirmation'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='scheduled', max_length=30, verbose_name='حالة الجلسة'),
        ),
        migrations.RunPython(populate_session_directions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('exchange', 'offer'), name='unique_exchange_offer_session'),
        ),
    ]
