# Generated by Django 6.0.7 on 2026-08-28 01:41

from django.db import migrations, models


def mark_existing_sessions_as_legacy(apps, schema_editor):
    apps.get_model('exchanges', 'Session').objects.update(uses_reward_system=False)


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0005_finalize_legacy_transferred_exchanges'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='reward_processed',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='session',
            name='rewarded_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='uses_reward_system',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.RunPython(mark_existing_sessions_as_legacy, migrations.RunPython.noop),
    ]
