# Generated by Django 6.0.7 on 2026-08-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0006_session_reward_processed_session_rewarded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='provider_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Provider seen at'),
        ),
    ]
