# Generated by Django 6.1 on 2026-08-23 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.PositiveIntegerField(default=0, verbose_name='درجة التطابق')),
                ('is_seen', models.BooleanField(default=False, verbose_name='تمت مشاهدة الاقتراح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاقتراح')),
                ('matched_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_for_users', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المقترح')),
                ('offered_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_offered_matches', to='skills.skill', verbose_name='المهارة المقدمة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_suggestions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('wanted_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_wanted_matches', to='skills.skill', verbose_name='المهارة المطلوبة')),
            ],
            options={
                'verbose_name': 'اقتراح تطابق',
                'verbose_name_plural': 'اقتراحات التطابق',
                'ordering': ['-match_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='skills.skilloffer', verbose_name='عرض المهارة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_offers', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'عرض محفوظ',
                'verbose_name_plural': 'العروض المحفوظة',
                'constraints': [models.UniqueConstraint(fields=('user', 'offer'), name='unique_favorite_offer')],
            },
        ),
        migrations.CreateModel(
            name='FavoriteProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to=settings.AUTH_USER_MODEL, verbose_name='مقدم المهارة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_providers', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مقدم مهارة محفوظ',
                'verbose_name_plural': 'مقدمو المهارات المحفوظون',
                'constraints': [models.UniqueConstraint(fields=('user', 'provider'), name='unique_favorite_provider')],
            },
        ),
    ]
