# Generated by Django 6.1 on 2026-08-23 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('individual', 'فرد'), ('professional', 'محترف'), ('trainer', 'مدرب'), ('organization', 'منظمة')], default='individual', max_length=20, verbose_name='نوع الحساب')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='accounts/profile_images/', verbose_name='الصورة الشخصية')),
                ('bio', models.TextField(blank=True, verbose_name='نبذة شخصية')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='الدولة')),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=100, verbose_name='المنطقة الزمنية')),
                ('preferred_language', models.CharField(default='ar', max_length=20, verbose_name='اللغة المفضلة')),
                ('is_verified', models.BooleanField(default=False, verbose_name='حساب موثق')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح لتقديم المهارات')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='متوسط التقييم')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='عدد التقييمات')),
                ('completed_sessions', models.PositiveIntegerField(default=0, verbose_name='الجلسات المكتملة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء الملف')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف مستخدم',
                'verbose_name_plural': 'ملفات المستخدمين',
                'ordering': ['-created_at'],
            },
        ),
    ]
