# Generated by Django 6.0.7 on 2026-08-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('professional', 'Professional'), ('trainer', 'Trainer'), ('organization', 'Organization')], default='individual', max_length=20, verbose_name='نوع الحساب'),
        ),
    ]
