# Generated by Django 6.1 on 2026-08-23 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HourWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الرصيد المتاح')),
                ('held_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الرصيد المحجوز')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي الساعات المكتسبة')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إجمالي الساعات المستخدمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hour_wallet', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'محفظة ساعات',
                'verbose_name_plural': 'محافظ الساعات',
            },
        ),
        migrations.CreateModel(
            name='HourTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('welcome', 'رصيد ترحيبي'), ('earned', 'ساعات مكتسبة'), ('spent', 'ساعات مستخدمة'), ('hold', 'حجز ساعات'), ('release', 'فك حجز'), ('refund', 'استرداد'), ('adjustment', 'تعديل إداري'), ('bonus', 'مكافأة')], max_length=20, verbose_name='نوع العملية')),
                ('direction', models.CharField(choices=[('credit', 'إضافة'), ('debit', 'خصم')], max_length=10, verbose_name='اتجاه العملية')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='عدد الساعات')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الرصيد بعد العملية')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='رقم المرجع')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='وصف العملية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية')),
                ('exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='exchanges.exchangerequest', verbose_name='طلب التبادل')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.hourwallet', verbose_name='المحفظة')),
            ],
            options={
                'verbose_name': 'حركة ساعات',
                'verbose_name_plural': 'حركات الساعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HourHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الساعات المحجوزة')),
                ('status', models.CharField(choices=[('active', 'محجوز'), ('captured', 'تم التحويل'), ('released', 'تم فك الحجز'), ('cancelled', 'ملغي')], default='active', max_length=20, verbose_name='حالة الحجز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الحجز')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت فك الحجز')),
                ('exchange', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='hour_hold', to='exchanges.exchangerequest', verbose_name='طلب التبادل')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='wallet.hourwallet', verbose_name='المحفظة')),
            ],
            options={
                'verbose_name': 'حجز ساعات',
                'verbose_name_plural': 'حجوزات الساعات',
                'ordering': ['-created_at'],
            },
        ),
    ]
