# Generated by Django 6.0.7 on 2026-08-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_welcome_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourhold',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('captured', 'Captured'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='حالة الحجز'),
        ),
        migrations.AlterField(
            model_name='hourtransaction',
            name='direction',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10, verbose_name='اتجاه العملية'),
        ),
        migrations.AlterField(
            model_name='hourtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('welcome', 'Welcome bonus'), ('earned', 'Earned'), ('spent', 'Spent'), ('hold', 'Hold'), ('release', 'Release'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('bonus', 'Bonus')], max_length=20, verbose_name='نوع العملية'),
        ),
        migrations.AlterField(
            model_name='hourwallet',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10, verbose_name='الرصيد المتاح'),
        ),
    ]
