# Generated by Django 6.0.7 on 2026-08-26 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_hold_directions(apps, schema_editor):
    HourHold = apps.get_model('wallet', 'HourHold')
    for hold in HourHold.objects.select_related('exchange').iterator():
        hold.payee_id = hold.exchange.provider_id
        hold.offer_id = hold.exchange.offer_id
        hold.save(update_fields=['payee', 'offer'])


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0004_exchangerequest_reverse_offer_session_learner_and_more'),
        ('skills', '0003_alter_skilloffer_delivery_method_and_more'),
        ('wallet', '0003_alter_hourhold_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hourhold',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hour_holds', to='skills.skilloffer', verbose_name='Skill offer'),
        ),
        migrations.AddField(
            model_name='hourhold',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_hour_holds', to=settings.AUTH_USER_MODEL, verbose_name='Hour recipient'),
        ),
        migrations.AlterField(
            model_name='hourhold',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hour_holds', to='exchanges.exchangerequest', verbose_name='طلب التبادل'),
        ),
        migrations.RunPython(populate_hold_directions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='hourhold',
            constraint=models.UniqueConstraint(fields=('exchange', 'wallet', 'payee', 'offer'), name='unique_exchange_direction_hold'),
        ),
    ]
