# Generated by Django 6.0.7 on 2026-08-27 23:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0005_finalize_legacy_transferred_exchanges'),
        ('wallet', '0004_hourhold_offer_hourhold_payee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hourtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('exchange__isnull', False), ('transaction_type__in', ['hold', 'release', 'spent', 'earned'])), fields=('wallet', 'exchange', 'transaction_type'), name='unique_wallet_exchange_lifecycle_transaction'),
        ),
        migrations.AddConstraint(
            model_name='hourwallet',
            constraint=models.CheckConstraint(condition=models.Q(('available_balance__gte', 0)), name='wallet_available_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='hourwallet',
            constraint=models.CheckConstraint(condition=models.Q(('held_balance__gte', 0)), name='wallet_held_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='hourwallet',
            constraint=models.CheckConstraint(condition=models.Q(('total_earned__gte', 0)), name='wallet_earned_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='hourwallet',
            constraint=models.CheckConstraint(condition=models.Q(('total_spent__gte', 0)), name='wallet_spent_nonnegative'),
        ),
    ]
