# Generated by Django 6.1 on 2026-08-23 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم التصنيف')),
                ('description', models.TextField(blank=True, verbose_name='وصف التصنيف')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='الأيقونة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تصنيف مهارة',
                'verbose_name_plural': 'تصنيفات المهارات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المهارة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skills.skillcategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'مهارة',
                'verbose_name_plural': 'المهارات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان العرض')),
                ('description', models.TextField(verbose_name='تفاصيل العرض')),
                ('level', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم'), ('expert', 'خبير')], default='intermediate', max_length=20, verbose_name='مستوى مقدم المهارة')),
                ('delivery_method', models.CharField(choices=[('online', 'عن بعد'), ('in_person', 'حضوري'), ('both', 'عن بعد وحضوري')], default='online', max_length=20, verbose_name='طريقة تقديم الجلسة')),
                ('session_duration_minutes', models.PositiveIntegerField(default=60, verbose_name='مدة الجلسة بالدقائق')),
                ('hour_cost', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='تكلفة الجلسة بالساعات')),
                ('is_active', models.BooleanField(default=True, verbose_name='العرض متاح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='skills.skill', verbose_name='المهارة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_offers', to=settings.AUTH_USER_MODEL, verbose_name='مقدم المهارة')),
            ],
            options={
                'verbose_name': 'عرض مهارة',
                'verbose_name_plural': 'عروض المهارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_level', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم'), ('any', 'أي مستوى')], default='any', max_length=20, verbose_name='المستوى المطلوب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='الطلب نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='skills.skill', verbose_name='المهارة المطلوبة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wanted_skills', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مهارة مطلوبة',
                'verbose_name_plural': 'المهارات المطلوبة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_skill_per_category'),
        ),
        migrations.AddConstraint(
            model_name='skillrequest',
            constraint=models.UniqueConstraint(fields=('user', 'skill'), name='unique_wanted_skill_per_user'),
        ),
    ]
