# Generated by Django 6.0.7 on 2026-08-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_seed_skill_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilloffer',
            name='delivery_method',
            field=models.CharField(choices=[('online', 'Remote'), ('in_person', 'In person'), ('both', 'Remote and in person')], default='online', max_length=20, verbose_name='طريقة تقديم الجلسة'),
        ),
        migrations.AlterField(
            model_name='skilloffer',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20, verbose_name='مستوى مقدم المهارة'),
        ),
        migrations.AlterField(
            model_name='skillrequest',
            name='desired_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('any', 'Any level')], default='any', max_length=20, verbose_name='المستوى المطلوب'),
        ),
    ]
